project_id = "jwddiyuezqrpuakazvgg"

[functions.realtime-transcription]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.whatsapp-api]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.document-tracking]
verify_jwt = false

[functions.pagarme-checkout]
verify_jwt = false

[functions.pagarme-webhook]
verify_jwt = false

[functions.pagarme-cancel]
verify_jwt = false

[functions.admin-impersonate]
verify_jwt = false

[functions.get-shared-content]
verify_jwt = false

[functions.track-email-link]
verify_jwt = false

[functions.whatsapp-public-api]
verify_jwt = false

[functions.tts-openai]
verify_jwt = false

[functions.form-capture]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false

