
-- ============================================================
-- NEW EMAIL TEMPLATES
-- ============================================================

-- 1. Plan Upgraded
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0001-4000-8000-000000000001', 'Upgrade de Plano Confirmado', 'Email enviado quando usuario faz upgrade do plano', 'financeiro',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#3A00E5 0%,#6B3AFF 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Upgrade Confirmado!</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Seu plano foi atualizado com sucesso para <strong>{{nome_plano}}</strong>! Agora voce tem acesso a todos os recursos inclusos no novo plano.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;text-align:center;"><p style="color:#16a34a;font-size:14px;font-weight:600;margin:0;">Novo Plano</p><p style="color:#15803d;font-size:24px;font-weight:700;margin:8px 0;">{{nome_plano}}</p><p style="color:#16a34a;font-size:16px;margin:0;">{{valor_fatura}}/{{ciclo_cobranca}}</p></td></tr></table><p style="color:#4a4a4a;font-size:16px;line-height:1.7;">Recursos desbloqueados:</p><ul style="color:#4a4a4a;font-size:15px;line-height:2;margin:0 0 20px;padding-left:20px;"><li>Todos os modulos Omni, Flow, Track e Suite</li><li>Envio ilimitado de emails e WhatsApp</li><li>Agentes de IA personalizados</li><li>Rastreamento avancado de documentos</li></ul><p style="text-align:center;margin:32px 0;"><a href="https://www.ellosuit.online/dashboard" style="display:inline-block;background:linear-gradient(135deg,#3A00E5,#6B3AFF);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Explorar Meu Novo Plano</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 2. Subscription Renewed
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0002-4000-8000-000000000002', 'Assinatura Renovada', 'Email enviado quando assinatura e renovada automaticamente', 'financeiro',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#3A00E5 0%,#6B3AFF 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Assinatura Renovada</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Sua assinatura do plano <strong>{{nome_plano}}</strong> foi renovada automaticamente com sucesso!</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8f7ff;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:8px 0;color:#666;font-size:14px;">Plano</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;font-weight:600;">{{nome_plano}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Valor</td><td style="padding:8px 0;color:#3A00E5;font-size:18px;text-align:right;font-weight:700;">{{valor_fatura}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Proxima renovacao</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;">{{proxima_cobranca}}</td></tr></table></td></tr></table><p style="color:#4a4a4a;font-size:16px;line-height:1.7;">Continue aproveitando todos os recursos do Ellosuit!</p><p style="text-align:center;margin:32px 0;"><a href="https://www.ellosuit.online/dashboard" style="display:inline-block;background:linear-gradient(135deg,#3A00E5,#6B3AFF);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Acessar Dashboard</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 3. Payment Failed / Retry
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0003-4000-8000-000000000003', 'Falha no Pagamento', 'Email enviado quando cobranca falha', 'financeiro',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#dc2626 0%,#ef4444 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Falha no Pagamento</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Nao conseguimos processar o pagamento da sua assinatura. Isso pode acontecer por saldo insuficiente, cartao expirado ou limite excedido.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#fef2f2;border:1px solid #fecaca;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><p style="color:#991b1b;font-size:14px;margin:0 0 8px;font-weight:600;">O que fazer:</p><ul style="color:#7f1d1d;font-size:14px;line-height:2;margin:0;padding-left:20px;"><li>Verifique se seu cartao esta valido</li><li>Confira o limite disponivel</li><li>Tente atualizar o metodo de pagamento</li></ul></td></tr></table><p style="color:#4a4a4a;font-size:14px;line-height:1.6;margin:0 0 20px;">Tentaremos cobrar novamente em 3 dias. Se o pagamento nao for regularizado, seu acesso podera ser suspenso.</p><p style="text-align:center;margin:32px 0;"><a href="https://www.ellosuit.online/dashboard/assinatura" style="display:inline-block;background:linear-gradient(135deg,#dc2626,#ef4444);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Atualizar Pagamento</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 4. Subscription Canceled by User
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0004-4000-8000-000000000004', 'Cancelamento Confirmado', 'Email enviado quando usuario cancela assinatura', 'financeiro',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#6b7280 0%,#9ca3af 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Cancelamento Confirmado</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Confirmamos o cancelamento da sua assinatura do plano <strong>{{nome_plano}}</strong>. Sentiremos sua falta!</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f4f6;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><p style="color:#4b5563;font-size:14px;margin:0 0 8px;">Voce ainda tem acesso ate:</p><p style="color:#1f2937;font-size:20px;font-weight:700;margin:0;">{{proxima_cobranca}}</p><p style="color:#6b7280;font-size:13px;margin:8px 0 0;">Apos essa data, sua conta voltara ao plano gratuito.</p></td></tr></table><p style="color:#4a4a4a;font-size:16px;line-height:1.7;">Seus dados serao mantidos por 90 dias. Voce pode reativar a qualquer momento e recuperar tudo.</p><p style="text-align:center;margin:32px 0;"><a href="https://www.ellosuit.online/dashboard/assinatura" style="display:inline-block;background:linear-gradient(135deg,#3A00E5,#6B3AFF);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Reativar Minha Assinatura</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 5. New Contact Registered (CRM)
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0005-4000-8000-000000000005', 'Novo Contato Cadastrado', 'Email de confirmacao quando novo contato entra no CRM', 'crm',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#FF4500 0%,#FF6B35 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Cadastro Recebido!</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Recebemos seu cadastro com sucesso! Agora voce faz parte da nossa base de contatos e em breve entraremos em contato com mais informacoes.</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;">Agradecemos seu interesse!</p><p style="text-align:center;margin:32px 0;"><a href="https://www.ellosuit.online" style="display:inline-block;background:linear-gradient(135deg,#FF4500,#FF6B35);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Conhecer o Ellosuit</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 6. Meeting Scheduled
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0006-4000-8000-000000000006', 'Reuniao Agendada', 'Email enviado quando uma reuniao e agendada via booking link', 'agendamento',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#007DE3 0%,#3B9AFF 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Reuniao Confirmada</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Sua reuniao foi agendada com sucesso!</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:8px 0;color:#666;font-size:14px;">Titulo</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;font-weight:600;">{{titulo_reuniao}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Data</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;">{{data_reuniao}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Horario</td><td style="padding:8px 0;color:#007DE3;font-size:18px;text-align:right;font-weight:700;">{{horario_reuniao}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Duracao</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;">{{duracao_reuniao}}</td></tr></table></td></tr></table><p style="text-align:center;margin:32px 0;"><a href="{{link_reuniao}}" style="display:inline-block;background:linear-gradient(135deg,#007DE3,#3B9AFF);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Entrar na Reuniao</a></p><p style="color:#888;font-size:13px;text-align:center;">Adicione este evento ao seu calendario para nao esquecer!</p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 7. Meeting Reminder
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0007-4000-8000-000000000007', 'Lembrete de Reuniao', 'Lembrete enviado 30 min antes da reuniao', 'agendamento',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#f59e0b 0%,#d97706 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Sua Reuniao Comeca em Breve!</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Este e um lembrete de que sua reuniao <strong>{{titulo_reuniao}}</strong> comeca em 30 minutos.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#fffbeb;border:1px solid #fde68a;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;text-align:center;"><p style="color:#92400e;font-size:32px;font-weight:700;margin:0;">{{horario_reuniao}}</p><p style="color:#b45309;font-size:14px;margin:8px 0 0;">{{data_reuniao}}</p></td></tr></table><p style="text-align:center;margin:32px 0;"><a href="{{link_reuniao}}" style="display:inline-block;background:linear-gradient(135deg,#f59e0b,#d97706);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Entrar Agora</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 8. Document Shared
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0008-4000-8000-000000000008', 'Documento Compartilhado', 'Email enviado quando documento/proposta e compartilhado', 'documentos',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#3A9A1C 0%,#4CAF50 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Documento Compartilhado</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Um documento foi compartilhado com voce:</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;text-align:center;"><p style="color:#15803d;font-size:18px;font-weight:600;margin:0;">{{nome_documento}}</p><p style="color:#16a34a;font-size:14px;margin:8px 0 0;">Enviado por {{nome_remetente}}</p></td></tr></table><p style="text-align:center;margin:32px 0;"><a href="{{link_documento}}" style="display:inline-block;background:linear-gradient(135deg,#3A9A1C,#4CAF50);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Abrir Documento</a></p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 9. Proposal / Service Order Sent
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0009-4000-8000-000000000009', 'Proposta Enviada', 'Email enviado quando proposta/OS e enviada ao cliente', 'documentos',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#3000E3 0%,#5B3AFF 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Nova Proposta</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Segue em anexo a proposta <strong>{{numero_proposta}}</strong> referente aos servicos solicitados.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8f7ff;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:8px 0;color:#666;font-size:14px;">Proposta</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;font-weight:600;">{{numero_proposta}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Valor Total</td><td style="padding:8px 0;color:#3000E3;font-size:18px;text-align:right;font-weight:700;">{{valor_proposta}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Validade</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;">{{validade_proposta}}</td></tr></table></td></tr></table><p style="text-align:center;margin:32px 0;"><a href="{{link_proposta}}" style="display:inline-block;background:linear-gradient(135deg,#3000E3,#5B3AFF);color:#ffffff;text-decoration:none;padding:16px 40px;border-radius:8px;font-size:16px;font-weight:600;">Ver Proposta Completa</a></p><p style="color:#888;font-size:13px;line-height:1.6;text-align:center;">Em caso de duvidas, responda este email.</p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- 10. Refund Processed
INSERT INTO public.email_templates (id, name, description, category, html_content, is_active, user_id, company_id) VALUES
('b1000001-0010-4000-8000-000000000010', 'Reembolso Processado', 'Email de confirmacao de reembolso', 'financeiro',
'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;"><tr><td align="center" style="padding:40px 20px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);"><tr><td style="background:linear-gradient(135deg,#3A00E5 0%,#6B3AFF 100%);padding:40px 40px 30px;text-align:center;"><img src="https://ellosuit-connect-vista.lovable.app/images/ellosuit-logo.png" alt="Ellosuit" width="180" style="display:inline-block;max-width:180px;height:auto;filter:brightness(0) invert(1);"></td></tr><tr><td style="padding:40px;"><h1 style="color:#1a1a1a;font-size:28px;margin:0 0 16px;text-align:center;">Reembolso Processado</h1><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Ola <strong>{{nome_cliente}}</strong>,</p><p style="color:#4a4a4a;font-size:16px;line-height:1.7;margin:0 0 20px;">Seu reembolso foi processado com sucesso. O valor sera creditado em sua conta em ate 10 dias uteis.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;margin:24px 0;"><tr><td style="padding:24px;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:8px 0;color:#666;font-size:14px;">Valor Reembolsado</td><td style="padding:8px 0;color:#16a34a;font-size:18px;text-align:right;font-weight:700;">{{valor_fatura}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">ID Transacao</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;font-family:monospace;">{{id_transacao}}</td></tr><tr><td style="padding:8px 0;color:#666;font-size:14px;">Prazo</td><td style="padding:8px 0;color:#1a1a1a;font-size:14px;text-align:right;">Ate 10 dias uteis</td></tr></table></td></tr></table><p style="color:#888;font-size:13px;line-height:1.6;text-align:center;">Em caso de duvidas sobre o reembolso, entre em contato conosco.</p></td></tr><tr><td style="background-color:#f9f9f9;padding:24px 40px;text-align:center;border-top:1px solid #eee;"><p style="color:#888;font-size:12px;margin:0;">2025 Ellosuit. Todos os direitos reservados.</p></td></tr></table></td></tr></table></body></html>',
true, 'c63ba931-0c34-4461-ae8d-2908aed7dd20', '60008c43-e536-482d-a090-91904de57534');

-- ============================================================
-- NEW AUTOMATIONS
-- ============================================================

INSERT INTO public.automations (company_id, created_by, name, description, trigger_type, trigger_config, actions, is_active, nodes, edges) VALUES
-- Upgrade de Plano
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Upgrade de Plano',
 'Envia email de confirmacao quando usuario faz upgrade do plano',
 'subscription_change', '{"event": "plan.upgraded"}',
 '[{"type": "send_email", "config": {"template_key": "plan_upgraded", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Upgrade de Plano","trigger_type":"subscription_change"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Email Upgrade","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Assinatura Renovada
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Assinatura Renovada',
 'Envia email automatico quando assinatura e renovada pelo Pagar.me',
 'webhook', '{"event": "subscription.renewed", "provider": "pagarme"}',
 '[{"type": "send_email", "config": {"template_key": "subscription_renewed", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Assinatura Renovada","trigger_type":"webhook"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Email Renovacao","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Falha no Pagamento
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Falha no Pagamento',
 'Envia alerta quando cobranca do cartao falha, pedindo atualizacao do metodo de pagamento',
 'webhook', '{"event": "charge.payment_failed", "provider": "pagarme"}',
 '[{"type": "send_email", "config": {"template_key": "payment_failed", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Cobranca Falhou","trigger_type":"webhook"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Alertar Cliente","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Cancelamento Confirmado
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Cancelamento Confirmado',
 'Envia confirmacao e incentivo de reativacao quando usuario cancela assinatura',
 'webhook', '{"event": "subscription.canceled", "provider": "pagarme"}',
 '[{"type": "send_email", "config": {"template_key": "cancellation_confirmed", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Assinatura Cancelada","trigger_type":"webhook"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Confirmacao Cancelamento","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Novo Contato via Formulario
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Novo Contato CRM',
 'Envia email de confirmacao quando novo contato se cadastra via formulario externo ou pixel',
 'new_client', '{"event": "client.created", "source": "form"}',
 '[{"type": "send_email", "config": {"template_key": "new_contact", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Novo Contato Cadastrado","trigger_type":"new_client"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Email de Confirmacao","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Reuniao Agendada
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Reuniao Agendada',
 'Envia confirmacao automatica quando reuniao e agendada via link de booking',
 'calendar_event', '{"event": "meeting.scheduled"}',
 '[{"type": "send_email", "config": {"template_key": "meeting_scheduled", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Reuniao Agendada","trigger_type":"calendar_event"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Confirmacao","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Lembrete de Reuniao
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Lembrete de Reuniao',
 'Envia lembrete 30 minutos antes da reuniao com link de acesso',
 'scheduled', '{"schedule": "meeting_reminder_30min"}',
 '[{"type": "send_email", "config": {"template_key": "meeting_reminder", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"30 Min para Reuniao","trigger_type":"scheduled"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Lembrete","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Documento Compartilhado
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Documento Compartilhado',
 'Envia email quando documento ou proposta e compartilhado com cliente',
 'document_event', '{"event": "document.shared"}',
 '[{"type": "send_email", "config": {"template_key": "document_shared", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Documento Compartilhado","trigger_type":"document_event"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar por Email","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Proposta Enviada
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Proposta/OS Enviada',
 'Envia proposta ou ordem de servico por email automaticamente ao cliente',
 'document_event', '{"event": "proposal.sent"}',
 '[{"type": "send_email", "config": {"template_key": "proposal_sent", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Proposta Criada","trigger_type":"document_event"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Proposta por Email","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]'),

-- Reembolso Processado
('60008c43-e536-482d-a090-91904de57534', 'c63ba931-0c34-4461-ae8d-2908aed7dd20',
 'Email - Reembolso Processado',
 'Envia confirmacao automatica quando reembolso e processado',
 'webhook', '{"event": "charge.refunded", "provider": "pagarme"}',
 '[{"type": "send_email", "config": {"template_key": "refund_processed", "from_email": "contato@ellosuit.com"}}]', true,
 '[{"id":"t1","type":"trigger","position":{"x":250,"y":50},"data":{"label":"Reembolso Processado","trigger_type":"webhook"}},{"id":"a1","type":"action","position":{"x":250,"y":200},"data":{"label":"Enviar Confirmacao Reembolso","action_type":"send_email"}}]',
 '[{"id":"e1","source":"t1","target":"a1"}]');
